name: Add Reviewer as Assignee and Set Project Status

on:
  pull_request:
    types: [ review_requested, review_request_removed ]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $EVENT_CONTEXT
