name: Add Reviewer as Assignee and Set Project Status

on:
  pull_request:
    types: [ review_requested, review_request_removed ]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          REQUESTED_REVIEWER: ${{ github.event.pull_request.requested_reviewer }}
        run: |
          echo $EVENT_CONTEXT
          gh pr edit $PR_URL --add-assignee $REQUESTED_REVIEWER

