name: Pull request test

on:
  pull_request:
    types: [ review_requested, review_request_removed ]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract PR information
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"

          # Convert assignees and requested reviewers to JSON
          ASSIGNEES_JSON='${{ toJson(github.event.pull_request.assignees) }}'
          REVIEWERS_JSON='${{ toJson(github.event.pull_request.requested_reviewers) }}'

          # Check if there are any assignees and remove them
          if [ "$ASSIGNEES_JSON" != "[]" ]; then
            echo "Removing current assignees..."
            echo "$ASSIGNEES_JSON" | jq -c '.[]' | while read -r assignee; do
              ASSIGNEE_LOGIN=$(echo "$assignee" | jq -r '.login')
              echo "Removing assignee: $ASSIGNEE_LOGIN"
              gh pr edit "$PR_NUMBER" --remove-assignees "$ASSIGNEE_LOGIN"
            done
          else
            echo "No assignees to remove."
          fi

          # Check if there are any requested reviewers and add them as assignees
          if [ "$REVIEWERS_JSON" != "[]" ]; then
            echo "Adding requested reviewers as assignees..."
            echo "$REVIEWERS_JSON" | jq -c '.[]' | while read -r reviewer; do
              REVIEWER_LOGIN=$(echo "$reviewer" | jq -r '.login')
              echo "Adding reviewer: $REVIEWER_LOGIN"
              gh pr edit "$PR_NUMBER" --add-assignees "$REVIEWER_LOGIN"
            done
          else
            echo "No reviewers to add as assignees."
          fi
