name: Pull request test

on:
  pull_request:
    types: [ review_requested, review_request_removed ]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          for assignee in ${{ github.event.pull_request.assignees }}; do
            gh pr edit $PR_URL --remove-assignee $assignee.login
          done
          for reviewer in ${{ github.event.pull_request.requested_reviewers }}; do
            gh pr edit $PR_URL --add-assignee $reviewer.login
          done
